"""Emit image-generation prompts for every design in the catalog.

    python3 src/prompts.py                      # all designs, generic prose
    python3 src/prompts.py --tiers A
    python3 src/prompts.py --format midjourney
    python3 src/prompts.py --out build/prompts.md

The style block is the part that matters. Image generators default to
gradients, soft shading and drop shadows, and every one of those ruins a DTF
print: partial opacity in the artwork becomes a speckled white underbase on the
shirt (docs/04-artwork-spec.md). The negative constraints are doing more work
here than the positive ones.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog import load  # noqa: E402

PROMPTS_PATH = Path(__file__).resolve().parent.parent / "catalog" / "art-prompts.csv"

# The constant half of every prompt.
STYLE = (
    "flat vector illustration, bold uniform black outlines, three flat colours "
    "maximum, mid-century screen-print poster style, warm and friendly, "
    "no gradients, no shading, no drop shadows, no glow, no texture, no grain, "
    "plain white background, centred with even margin, entire object in frame, "
    "no text, no letters, no watermark"
)

# For generators that take a separate negative prompt.
NEGATIVE = (
    "gradient, shading, shadow, drop shadow, glow, texture, noise, grain, "
    "photorealistic, 3d render, watercolour, pencil sketch, cross-hatching, "
    "background scenery, horizon, text, letters, numbers, watermark, "
    "signature, soft edges, blur, semi-transparent"
)

PALETTE_NOTE = (
    "If you want colour, pick ONE accent and keep it the same across every "
    "design. A catalog in one palette reads as a brand; a catalog in thirty "
    "palettes reads as a clip-art folder."
)


def load_subjects() -> dict[str, str]:
    with PROMPTS_PATH.open(newline="", encoding="utf-8") as fh:
        return {r["id"]: r["subject"] for r in csv.DictReader(fh)}


def build(subject: str, fmt: str) -> str:
    if fmt == "midjourney":
        return (
            f"{subject}, {STYLE} --no gradients, shadows, text, background "
            f"--style raw --ar 1:1 --stylize 150"
        )
    if fmt == "sd":
        return f"{subject}, {STYLE}\n    NEGATIVE: {NEGATIVE}"
    if fmt == "dalle":
        # Conversational models follow prose better than keyword soup.
        return (
            f"Draw {subject}. Make it a simple flat illustration in the style "
            f"of a screen-printed t-shirt graphic: bold even outlines, at most "
            f"three flat colours, and absolutely no gradients, shading, drop "
            f"shadows or texture. Plain white background. Centre it with an "
            f"even margin and include no text of any kind."
        )
    return f"{subject}, {STYLE}"


def render_markdown(rows: list[tuple], fmt: str) -> str:
    out = [
        "# Image generation prompts",
        "",
        f"Generated by `src/prompts.py --format {fmt}`. One prompt per design.",
        "",
        "## Before you start",
        "",
        "- Generate at the **largest size the tool offers**. You are printing at",
        "  12 inches wide and 300 DPI, which is 3600px. Upscaling a small render",
        "  adds mush, not detail.",
        "- Generate 4 variations and keep the one with the cleanest edges, not",
        "  the one with the most detail. Detail is what breaks in DTF.",
        f"- {PALETTE_NOTE}",
        "- Save each result as `<motif>.svg` after tracing, then run",
        "  `python3 src/art.py --art-dir my-art/`. The motif name for each design",
        "  is in the table below.",
        "",
        "## After you generate",
        "",
        "1. Remove the background so it is genuinely transparent, not white.",
        "2. Harden the alpha. No feathered edges, no semi-transparent pixels.",
        "3. Trace to vector (Illustrator Image Trace, Inkscape Trace Bitmap, or",
        "   a paid vectoriser).",
        "4. Name it `<motif>.svg` and drop it in your art directory.",
        "",
        "## The style block",
        "",
        "Every prompt below already ends with this. Reuse it verbatim for any",
        "new design so the catalog stays visually consistent:",
        "",
        "```",
        STYLE,
        "```",
        "",
        "Negative prompt, for tools that take one separately:",
        "",
        "```",
        NEGATIVE,
        "```",
        "",
        "## Prompts",
        "",
    ]
    for d, subject, prompt in rows:
        out += [
            f"### {d.id} — {d.slogan}",
            "",
            f"*tier {d.tier} · {d.tone} · save as `{d.motif}.svg`*",
            "",
            "```",
            prompt,
            "```",
            "",
        ]
    return "\n".join(out)


def main() -> None:
    p = argparse.ArgumentParser(description="Emit image-generation prompts.")
    p.add_argument("--tiers", nargs="+", default=["A", "B", "C"])
    p.add_argument("--format", choices=["generic", "midjourney", "dalle", "sd"],
                   default="generic")
    p.add_argument("--out", type=Path, default=None, help="write markdown here")
    args = p.parse_args()

    subjects = load_subjects()
    designs = [d for d in load() if d.tier in args.tiers]

    missing = [d.id for d in designs if d.id not in subjects]
    if missing:
        print(f"  ! no subject for: {', '.join(missing)}")

    rows = [
        (d, subjects[d.id], build(subjects[d.id], args.format))
        for d in designs if d.id in subjects
    ]

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(render_markdown(rows, args.format), encoding="utf-8")
        print(f"{len(rows)} prompts -> {args.out}")
        return

    for d, _, prompt in rows:
        print(f"\n--- {d.id}  {d.slogan}  (save as {d.motif}.svg)")
        print(prompt)
    print(f"\n{len(rows)} prompts, format={args.format}")
    print(f"\n{PALETTE_NOTE}")


if __name__ == "__main__":
    main()
